#ifndef PROJECTNAME_GLOBALCONSTANTS_H
#define PROJECTNAME_GLOBALCONSTANTS_H

#define WINDOW_HORIZONTAL_SIZE 640
#define WINDOW_VERTICAL_SIZE 480
#define WINDOW_TITLE "ProjectName"
#define FPS_LIMIT 60

#endif //PROJECTNAME_GLOBALCONSTANTS_H